#!/bin/bash
# (C) Copyright 2012,2013 Continuent, Inc - Released under the New BSD License
# Version 1.0.5 - 2013-04-03

cd `dirname $0`

MISSING=""
UNDOCUMENTED=""
for F in `cat MANIFEST` 
do
    COMMENT=$(echo $F |grep '#')
    if [ -n "$COMMENT" ]
    then
        echo $COMMENT
    else
        if [ -f $F ]
        then
            echo "ok $F"
        else
            echo "not ok - $F not found"
            MISSING="$MISSING $F"
        fi
        FOUND_IN_DOCS=$(grep $F REFERENCE.txt)
        if [ -z "$FOUND_IN_DOCS" ]
        then
            echo "not ok - '$F' not described in the documentation"
            UNDOCUMENTED="$UNDOCUMENTED $F"
        fi
    fi
done

for F in *
do
    IS_BAK=$(echo $F | perl -lne 'print 1 if /(~|\.bak)$/') 
    if [ -z "$IS_BAK" ]
    then
        LISTED=$(grep $F MANIFEST)
        if [ -z "$LISTED" ]
        then
            echo "WARNING: file $F not in MANIFEST"
        fi
    fi
done

exit_code=0
echo ""
if [ -z "$MISSING" ]
then
    echo "All files are accounted for"
else
    echo "**** WARNING ****"
    echo "** Missing files: $MISSING"
    echo "*****************"
    exit_code=1
fi

if [ -z "$UNDOCUMENTED" ]
then
    echo "All files are documented"
else
    echo "**** WARNING ****"
    echo "Undocumented files: $UNDOCUMENTED"
    echo "*****************"
    exit_code=1
fi

exit $exit_code

