#!/bin/bash
# (C) Copyright 2012,2013 Continuent, Inc - Released under the New BSD License
# Version 1.0.9 - 2013-12-18
cookbook_dir=$(dirname $0)
cd $cookbook_dir
cookbook_dir=$PWD
cd "$cookbook_dir/../"
$cookbook_dir/tool.sh multi_trepctl $@
